import { useState } from 'react'

import { ApprovalDecisionPanel, ApprovalMatrix, ApprovalStepper, TaskQueue } from '../components/document-routing/WorkflowComponents'
import { useToast } from '../components/feedback/ToastProvider'
import { FormField, SelectInput, Textarea } from '../components/forms/FormControls'
import { mockWorkflow } from '../data/mockDocuments'

export function DocumentRoutingPage() {
  const [mode, setMode] = useState('Sequential')
  const { notify } = useToast()
  return <div className="page"><div className="page-header"><div><span className="eyebrow">Review and approval</span><h1>Document routing</h1><p>Configure sequential or parallel workflows and simulate review decisions in local state.</p></div><button className="button primary" onClick={() => notify('Routing workflow started')}>Start routing</button></div><section className="panel"><div className="panel-heading"><div><span className="eyebrow">SOP-104</span><h2>Batch Record Review</h2></div><div className="segmented">{['Sequential', 'Parallel'].map((item) => <button className={mode === item ? 'active' : ''} onClick={() => setMode(item)} key={item}>{item}</button>)}</div></div><ApprovalStepper steps={mockWorkflow} /></section><div className="routing-grid"><section className="panel span-2"><div className="panel-heading"><h2>My approval task</h2><span className="status-badge warning">Due in 2 days</span></div><div className="review-summary"><div><span>Document</span><strong>SOP-104 · Batch Record Review</strong></div><div><span>Current assignment</span><strong>QA approval</strong></div><div><span>Owner</span><strong>Maya Chen</strong></div></div><FormField label="Review remarks"><Textarea placeholder="Record a clear, attributable review comment…" /></FormField><ApprovalDecisionPanel onDecision={(decision) => notify(`${decision} recorded in mock workflow`)} /></section><aside className="panel"><div className="panel-heading"><h2>Pending queue</h2></div><TaskQueue steps={mockWorkflow.slice(2)} /><div className="notification warning"><strong>Escalation reminder</strong><p>One task is within 48 hours of its due date.</p></div></aside></div><div className="two-column"><section className="panel"><div className="panel-heading"><h2>Route configuration</h2></div><div className="form-grid"><FormField label="Reviewer"><SelectInput><option>Jordan Lee</option><option>Priya Shah</option></SelectInput></FormField><FormField label="Approver"><SelectInput><option>Alex Brooks</option><option>Avery Morgan</option></SelectInput></FormField><FormField label="QA"><SelectInput><option>Priya Shah</option></SelectInput></FormField><FormField label="Due-date rule"><SelectInput><option>3 business days per step</option><option>5 business days per step</option></SelectInput></FormField></div></section><section className="panel"><div className="panel-heading"><h2>Approval matrix</h2></div><ApprovalMatrix /></section></div></div>
}

