import { useState } from 'react'

import { useToast } from '../components/feedback/ToastProvider'
import { FormField, SelectInput, TextInput } from '../components/forms/FormControls'
import { useAuth } from '../hooks/useAuth'

export function SettingsPage() {
  const [compact, setCompact] = useState(false)
  const { user } = useAuth()
  const { notify } = useToast()
  return <div className="page"><div className="page-header"><div><span className="eyebrow">Template configuration</span><h1>Settings</h1><p>Example preferences and adapter guidance for projects built from this starter.</p></div><button className="button primary" onClick={() => notify('Settings saved locally')}>Save settings</button></div><div className="settings-grid"><section className="panel"><div className="panel-heading"><h2>Profile</h2></div><div className="form-grid"><FormField label="Display name"><TextInput defaultValue={user?.name} /></FormField><FormField label="Email"><TextInput defaultValue={user?.email} /></FormField><FormField label="Role"><SelectInput defaultValue={user?.role}><option>Admin</option><option>Manager</option><option>Editor</option><option>Viewer</option></SelectInput></FormField><FormField label="Timezone"><SelectInput><option>Asia/Taipei</option><option>UTC</option><option>America/New_York</option></SelectInput></FormField></div></section><section className="panel"><div className="panel-heading"><h2>Interface</h2></div><label className="setting-row"><div><strong>Compact tables</strong><p>Reduce row height for dense operational data.</p></div><input type="checkbox" checked={compact} onChange={(event) => setCompact(event.target.checked)} /></label><label className="setting-row"><div><strong>Email notifications</strong><p>Example preference for a future notification adapter.</p></div><input type="checkbox" defaultChecked /></label><label className="setting-row"><div><strong>Statistical alert digest</strong><p>Summarize CPV signals once per day.</p></div><input type="checkbox" defaultChecked /></label></section><section className="panel span-2"><div className="panel-heading"><h2>Backend adapter checklist</h2></div><div className="adapter-grid">{[['Supabase', 'Replace mock services with typed Supabase repositories and enforce RLS.'], ['REST API', 'Implement the existing service interfaces with fetch and schema validation.'], ['Local JSON', 'Import fixtures into data modules or serve JSON from the public folder.'], ['E-signature provider', 'Map request, recipient, webhook, certificate, and download endpoints.']].map(([title, text]) => <article key={title}><span>→</span><div><strong>{title}</strong><p>{text}</p></div></article>)}</div></section></div></div>
}

