// Generated by scripts/import-vrms-csv.mjs — do not edit by hand
import bundle from './vrmsProductionData.json'
import type { AuditEvent, RegistryValue, RoutingDocument } from '../types/vrms'

export const VRMS_PRODUCTION_DEFAULT_REGISTRY = bundle.defaultRegistry

export const mockVrmsProfiles = bundle.profiles as Array<{
  id: string
  email: string
  displayName: string
  role: 'user' | 'admin'
}>

export const mockRegistryValues = bundle.registryValues as RegistryValue[]
export const mockRoutingDocuments = bundle.routingDocuments as RoutingDocument[]
export const mockAuditEvents = bundle.auditEvents as AuditEvent[]
